### ISSUE TITLE
Join room

### ISSUE THREAD

**Issue by dolwijit13** [WatcharitNew/Guess-What-You-Draw#3]
-join ห้อง ซักวิธี (code? / url?)

**Comment by WatcharitNew** [comment]
คิดว่าเป็น url ไปเลยดีกว่า โดยคนที่ยัง ไม่ได้ตั้งชื่อ จะเข้าไปหน้าตั้งชื่อก่อน แล้วค่อย redirect ไปหน้ารอห้อง

**Comment by dolwijit13** [comment]
- handle กรณีที่ join หลังเริ่มห้องไปแล้ว / join ห้องที่ไม่มีอยู่จริง (ขึ้น error?)

**Comment by WatcharitNew** [comment]
> * handle กรณีที่ join หลังเริ่มห้องไปแล้ว / join ห้องที่ไม่มีอยู่จริง (ขึ้น error?)

ตอนนี้มี2กรณีคือ เหมือนให้ user เปิดห้องใหม่เลย หรือขึ้นว่า ห้องที่จะเข้าได้เล่นจบไปแล้ว หรือกำลังเล่น กรุณารอรอบต่อไป กรณีที่ยังมีคนเล่นนะ และเมื่อจบเกม ต้องพากลับมาที่หน้ารอห้องเหมือนเดิม อยากได้แบบไหนดี
id อาจจะใช้ของ uuid เอา
